Post for customers
BaltejToorTJX/capstone-project pull request #2
Opened 2022-03-22 20:38 UTC by probabri

Wrote post api for customers. 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/76490401/159571224-37cbc46f-37e1-4a75-8bd9-7b972d74c024.png">

2022-03-22 20:58 UTC, BaltejToorTJX requested changes
Do we want to send a status code on successful calls as well? Checking to make sure so I can adjust moving forward. Also, let's change to using 404 for the error call in addition to passing the error instead of the generic message (unless there is a rationale for that that I'm unaware of).

You could also remove allowNull completely from customerNotes since the default behaviour is true anyways.

2022-03-23 12:43 UTC, probabri commented
So I updated the status codes - we probably don't want to do a 404 (we can discuss) and added success ones as appropriate. 
Removed allow null completely from the customer note model - good call

2022-03-23 12:58 UTC, BaltejToorTJX approved these changes

2022-03-23 13:01 UTC, danieltrying approved these changes
LGTM

2022-03-23 13:02 UTC, merged